### ISSUE TITLE
how to use gps to evaluation

### ISSUE THREAD

**Issue by limeng1523** [TixiaoShan/LIO-SAM#22]
Hi,
I want to use the gps provided by your data sets as the ground truth for evaluation, but its coordinate system and frequency are different from the system output, could you tell me how do you solve this? Thank you very much!

**Comment by TixiaoShan** [comment]
When you launch the system, there is one odometry published at ```odometry/gps```, which is the transformed GPS coordinates in Cartesian space. You can use that for evaluation.

**Comment by limeng1523** [comment]
@TixiaoShan Hi,
Thanks for your answer. I have found the topic /odometry/gps, but it can't coincide with the system output. It seems that there is a rotation between /odometry/gps and system output. Besides, during running the system, the gps position changed suddenly. Could you tell me where is the problem? Thank you very much!
![Screenshot from 2020-07-15 09-50-57](https://user-images.githubusercontent.com/36916945/87519190-8dc80c00-c681-11ea-8d88-576f30b1ab30.png)
![Screenshot from 2020-07-15 09-53-00](https://user-images.githubusercontent.com/36916945/87519196-8ef93900-c681-11ea-9eac-06d172772812.png)

**Comment by TixiaoShan** [comment]
You can set the ```gpsTopic``` correctly to subscribe to it. The GPS data in the dataset is very bad. It jumps a few hundred meters will corrupt the optimization.

**Comment by TixiaoShan** [comment]
https://github.com/TixiaoShan/LIO-SAM/issues/8

**Comment by Pallav1299** [comment]
I tried the package on **Campus dataset(small)**. When not using GPS, the package performs very well. 
Some results:
![image](https://user-images.githubusercontent.com/32015105/89147896-c159d000-d575-11ea-93ba-7ddd13f6395b.png)
![image](https://user-images.githubusercontent.com/32015105/89147885-b737d180-d575-11ea-9d49-ba8df34f0413.png)

On comparing the GPS odometry with the optimized path, both look quite similar. The initial rotation seems to be the only difference between the two.

But when using GPS, there are some serious artifacts in the output PCD. 
Some results:
![image](https://user-images.githubusercontent.com/32015105/89148103-755b5b00-d576-11ea-96aa-5d5e4dda7669.png)

Now I have the following questions:
1. Can we create correct(with least artifacts) global PCD map with LIO-SAM? 
2. Any method for evaluating LIO-SAM? (I tried evaluating with KITTI ground truth sequences, the elevation data was inconsistent: [LINK)](https://github.com/TixiaoShan/LIO-SAM/issues/35#issuecomment-664587989. But this can be misleading since we don't have correct IMU parameters for KITTI.)
3. How well does LIO-SAM support car-like vehicles?
