### ISSUE TITLE
Why the same error occurs when the rosbag play in normal speed

### ISSUE THREAD

**Issue by BayRanger** [TixiaoShan/LIO-SAM#272]
Hey, I just did some tests on the vins mono, lio-sam and lvi-sam.
[https://www.youtube.com/watch?v=FhcnIUbCqxQ&t=11s](url)
[https://www.youtube.com/watch?v=KHs6eGZinTw&t=136s](url)

It showed that lvi-sam always crashes  around the same location when running the dataset, so did vins mono. But, when I slow down the rosbag, the lvi-sam could work. 
So I am curious about the reason why the crashes happen, It seems to be deterministic instead of random, because the location where mistakes happen is almost the same.  I am glad to hear some opinions from you.

**Comment by Huguet57** [comment]
It seems like there are two situations going on here, right? On the LVI-SAM the IMU shifts 180 degrees and then does it again and tries to recover. With the VINS-Mono is the IMU estimates a bias of 5 meters (supposedly because of a bad feature association) and resets the system going to the origin.

Have you seen the IMU readings in that point? What it seems is that there is a big outlier there (going 5 meters backwards?) that makes everything crash. Have you checked?
