### ISSUE TITLE
LIO-SAM initialization problem

### ISSUE THREAD

**Issue by Yeah2333** [TixiaoShan/LIO-SAM#62]
@TixiaoShan  I have test LIO-SAM with mti-710，the result is wonderful. But I had a problem. When i start lio-sam with lidar and imu static，the result drift. What cause this problem？Is the external or internal parameters not accurate enough?But when i start lio-sam with motion ，the result is very good. 
![2020-08-07 10-41-34 的屏幕截图](https://user-images.githubusercontent.com/22851247/89750226-a818cc80-dafd-11ea-9311-98e0122b8b6e.png)

**Comment by TixiaoShan** [comment]
What kind of environment are you testing in?

**Comment by Yeah2333** [comment]
in a office

**Comment by TixiaoShan** [comment]
LIO-SAM doesn't work well in an indoor environment. Have you tried it outdoors?

**Comment by rohansingh42** [comment]
Does it have any tunable parameters that can improve indoor performance?

**Comment by TixiaoShan** [comment]
Not really. Most confined indoor environments are degraded for lidars with a small FOV.

**Comment by ClementPinard** [comment]
had the same problem in my own office. the key problem is that in an office you only see vertical surfaces (the wall). If you rotate the lidar so that it can see ceiling (or ground) and the vertical walls, it should be much more stable. There is still some unresolved bias : my scan shakes around the right position. I suspect that my IMU has some inner bias and thus when standing still the gravity is not exactly compensated, resulting in a constant acceleration that messes up the imu odometry. Shouldn't the imu preintegration module of gtsam takes it into account ? Or are the bias in the code just for velocity ?

**Comment by Yeah2333** [comment]
but i still have some question. i have test these scene using loam or a-loam，lego-loam，it wont drift，but in lio-sam，it drift dramatically，i think the imupreintegration  may have some bias，and because low point in map，scan to map can‘t lower the bias，so in the next ，the bias may be more massive，because last scan to map register a wrong scan 。 @TixiaoShan  @ClementPinard

**Comment by TixiaoShan** [comment]
@ClementPinard 
I also notice that if you are doing indoor mapping, reduce the ```mappingCornerLeafSize``` and ```mappingSurfLeafSize``` helps a lot.

**Comment by tenghooi** [comment]
> @ClementPinard
> I also notice that if you are doing indoor mapping, reduce the `mappingCornerLeafSize` and `mappingSurfLeafSize` helps a lot.


I reduce the 'mappingCornerLeafSize' and 'mappingSurfLeafSize' to 0.05 and 0.1 and find it works very well in indoor environment in Gazebo.  I made a video about it here [https://www.youtube.com/watch?v=aH4dnWnwABs](url)

I am new to SLAM. Would kindly explain what  'mappingCornerLeafSize' and 'mappingSurfLeafSize'  are?

![circular_features](https://user-images.githubusercontent.com/77495277/104734752-aeca0080-577b-11eb-9a47-5859401344d8.png)
